services:
    innmind_rest.listener.request:
        class: Innmind\RestBundle\EventListener\RequestListener
        arguments: [@innmind_rest.request.parser]
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.controller:
        class: Innmind\RestBundle\EventListener\ControllerListener
        arguments:
            - @innmind_rest.server.validator
            - @innmind_rest.request.parser
            - @event_dispatcher
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.storage.create:
        class: Innmind\Rest\Server\EventListener\StorageCreateListener
        arguments: [@property_access]
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.server.response.collection:
        class: Innmind\Rest\Server\EventListener\Response\CollectionListener
        arguments:
            - @router
            - @innmind_rest.server.route_loader
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.server.response.create:
        class: Innmind\Rest\Server\EventListener\Response\CreateListener
        arguments:
            - @router
            - @innmind_rest.server.route_loader
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.server.response.delete:
        class: Innmind\Rest\Server\EventListener\Response\DeleteListener

    innmind_rest.listener.server.response.options:
        class: Innmind\Rest\Server\EventListener\Response\OptionsListener
        arguments:
            - @router
            - @innmind_rest.server.route_loader
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.server.response.resource:
        class: Innmind\Rest\Server\EventListener\Response\ResourceListener
        arguments:
            - @router
            - @innmind_rest.server.route_loader
            - @serializer
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.server.response.capabilities:
        class: Innmind\RestBundle\EventListener\CapabilitiesResponseListener
        arguments:
            - @router
        tags:
            - { name: kernel.event_subscriber }
