services:
    innmind_rest.listener.request:
        class: Innmind\RestBundle\EventListener\RequestListener
        arguments: [@innmind_rest.request.parser]
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.controller:
        class: Innmind\RestBundle\EventListener\ControllerListener
        arguments:
            - @innmind_rest.server.validator
            - @innmind_rest.request.parser
        tags:
            - { name: kernel.event_subscriber }

    innmind_rest.listener.storage.create:
        class: Innmind\Rest\Server\EventListener\StorageCreateListener
        arguments: [@property_access]
        tags:
            - { name: kernel.event_subscriber }
