imports:
    - { resource: serializer.yml }
    - { resource: registry.yml }
    - { resource: storage.yml }

services:
    innmind_rest.formats:
        class: Innmind\Rest\Server\Formats

    innmind_rest.entity_builder:
        class: Innmind\Rest\Server\EntityBuilder
        arguments:
            - @property_accessor
            - @event_dipatcher

    innmind_rest.resource_builder:
        class: Innmind\Rest\Server\ResourceBuilder
        arguments:
            - @property_accessor
            - @event_dipatcher

    innmind_rest.request.parser:
        class: Innmind\Rest\Server\Request\Parser
        arguments:
            - @serializer
            - @innmind_rest.formats
            - @innmind_rest.negotiator

    innmind_rest.negotiator:
        class: Negotiation\Negotiator
        public: false
