services:
    innmind_rest.server.serializer.normalizer.resource:
        class: Innmind\Rest\Server\Serializer\Normalizer\ResourceNormalizer
        arguments:
            - '@innmind_rest.server.resource_builder'
        tags:
            - { name: serializer.normalizer }

    innmind_rest.server.serializer.encoder.json:
        class: Innmind\Rest\Server\Serializer\Encoder\JsonEncoder
        tags:
            - { name: serializer.encoder }
            - { name: innmind_rest.server.format, format: json, mime: application/json, priority: 10 }

    innmind_rest.server.serializer.encoder.form:
        class: Innmind\Rest\Server\Serializer\Encoder\FormEncoder
        tags:
            - { name: serializer.encoder }
            - { name: innmind_rest.server.format, format: form, mime: application/x-www-form-urlencoded }
