services:
    innmind_rest.server.storages:
        class: Innmind\Rest\Server\Storages

    innmind_rest.server.storage.abstract.neo4j:
        class: Innmind\Rest\Server\Storage\Neo4jStorage
        abstract: true
        arguments:
            - ~
            - @event_dispatcher
            - @innmind_rest.server.entity_builder
            - @innmind_rest.server.resource_builder

    innmind_rest.server.storage.abstract.doctrine:
        class: Innmind\Rest\Server\Storage\DoctrineStorage
        abstract: true
        arguments:
            - ~
            - @event_dispatcher
            - @innmind_rest.server.entity_builder
            - @innmind_rest.server.resource_builder
