language: php
php:
    - 5.5
    - 5.6
    - 7.0
before_script: composer install --no-dev --prefer-source
script: phpunit --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
    slack: innmind:nAiLaAi6RU4wGEAdL6FuKdyF
